### ISSUE TITLE
May I ask for your reference paper?

### ISSUE THREAD

**Issue by GarveyHung** [PuzhenYuan/carla-APF-control#1]
Hi, thank you for your code, it's an excellent work.
It would be nicer of you to share reference paper.

**Comment by PuzhenYuan** [comment]
Thanks for your kind words!
The APF construction is mainly based on this article: [The Driving Safety Field Based on Driver–Vehicle–Road Interactions](https://ieeexplore.ieee.org/abstract/document/7050373/), which is an early work to model risk in autonomous driving.
This kind of risk modeling also led to many different types of control methods, including MPC-based and gradient-based ones, etc.
